import { navbar } from "vuepress-theme-hope";

export default navbar([
  { text: "首页", link: "/" },
  { text: "学习路线", link: "/roadmap/" },
  {
    text: "语言基础",
    children: [
      { text: "Kotlin", link: "/language/kotlin/" },
      { text: "Java", link: "/language/java/" },
      { text: "C++ 知识点", link: "/language/cpp/" },
      { text: "设计模式", link: "/language/design-pattern/" },
      { text: "数据结构与算法", link: "/language/algorithm/" },
    ],
  },
  {
    text: "Android 核心",
    children: [
      { text: "Activity", link: "/android/activity/" },
      { text: "Service", link: "/android/service/" },
      { text: "BroadcastReceiver", link: "/android/broadcast/" },
      { text: "ContentProvider", link: "/android/content-provider/" },
      { text: "Fragment", link: "/android/fragment/" },
      { text: "Intent", link: "/android/intent/" },
      { text: "Application", link: "/android/app/" },
      { text: "资源系统", link: "/android/resource/" },
      { text: "权限系统", link: "/android/permission/" },
      { text: "通知机制", link: "/android/notification/" },
      { text: "Context", link: "/android/context/" },
      { text: "进程", link: "/android/process/" },
      { text: "数据存储", link: "/android/storage/" },
    ],
  },
  {
    text: "UI 与渲染",
    children: [
      { text: "View 体系", link: "/ui/view/" },
      { text: "事件分发机制", link: "/ui/event/" },
      { text: "自定义 View", link: "/ui/custom-view/" },
      { text: "Bitmap", link: "/ui/bitmap/" },
      { text: "Window", link: "/ui/window/" },
      { text: "动画机制", link: "/ui/animation/" },
      { text: "布局优化", link: "/ui/layout/" },
      { text: "渲染原理", link: "/ui/render/" },
    ],
  },
  {
    text: "Jetpack",
    children: [
      { text: "Jetpack Compose", link: "/jetpack/compose/" },
      { text: "Lifecycle / ViewModel", link: "/jetpack/lifecycle-viewmodel/" },
      { text: "Room / DataStore", link: "/jetpack/room-datastore/" },
      { text: "Paging / Navigation", link: "/jetpack/paging-navigation/" },
      { text: "WorkManager / Hilt", link: "/jetpack/workmanager-hilt/" },
      { text: "Activity 库", link: "/jetpack/activity/" },
      { text: "AppCompat 兼容库", link: "/jetpack/appcompat/" },
      { text: "Biometric 生物识别", link: "/jetpack/biometric/" },
      { text: "Collection 集合库", link: "/jetpack/collection/" },
      { text: "Core 核心库", link: "/jetpack/core/" },
      { text: "Fragment 库原理", link: "/jetpack/fragment/" },
    ],
  },
  {
    text: "网络与异步",
    children: [
      { text: "网络与协议", link: "/network/http/" },
      { text: "Handler 消息机制", link: "/network/handler/" },
      { text: "协程 Flow / RxJava", link: "/network/coroutine/" },
      { text: "线程池与并发", link: "/network/thread/" },
      { text: "计算机网络体系", link: "/network/osi-tcpip.html" },
      { text: "Socket 编程基础", link: "/network/socket.html" },
      { text: "TCP 与 UDP 详解", link: "/network/tcp-udp.html" },
    ],
  },
  {
    text: "进阶实战",
    children: [
      { text: "架构设计", link: "/advanced/architecture/" },
      { text: "组件化与模块化", link: "/advanced/modular/" },
      { text: "插件化与热修复", link: "/advanced/plugin/" },
      { text: "性能优化", link: "/advanced/performance/" },
      { text: "稳定性保障", link: "/advanced/stability/" },
      { text: "音视频开发", link: "/advanced/multimedia/" },
      { text: "跨端方案", link: "/advanced/cross-platform/" },
    ],
  },
  {
    text: "系统原理",
    children: [
      { text: "Binder 机制", link: "/system/binder/" },
      { text: "AMS / WMS", link: "/system/ams-wms/" },
      { text: "系统与应用启动流程", link: "/system/boot/" },
      { text: "APK 打包与签名", link: "/system/apk/" },
      { text: "ART / DEX / 类加载", link: "/system/art/" },
      { text: "操作系统", link: "/system/os/" },
      { text: "输入系统", link: "/system/input/" },
      { text: "电源与功耗", link: "/system/power/" },
      { text: "网络与连接", link: "/system/connectivity/" },
      { text: "存储系统", link: "/system/storage/" },
      { text: "音频系统", link: "/system/audio/" },
      { text: "图形显示系统", link: "/system/graphics/" },
      { text: "安全体系", link: "/system/security/" },
      { text: "HAL 硬件抽象层", link: "/system/hal/" },
    ],
  },
  {
    text: "工程实践",
    children: [
      { text: "Gradle 构建", link: "/engineering/gradle/" },
      { text: "Git 与版本管理", link: "/engineering/git/" },
      { text: "CI/CD", link: "/engineering/cicd/" },
      { text: "测试体系", link: "/engineering/testing/" },
    ],
  },
  { text: "面试指南", link: "/interview/" },
  { text: "实战项目", link: "/projects/" },
  { text: "书籍资源", link: "/books/" },
  {
    text: "GitHub",
    link: "https://github.com/galifans/wikiandroid",
  },
]);
